# Generated by Django 3.2 on 2021-05-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_tweets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweets',
            new_name='Tweeter',
        ),
    ]
